### PR TITLE
Add alternative worker commands, config options

### LINKED ISSUE #10: Add support for alternative worker commands and config options
Right now the `dask worker` command is hard coded.

https://github.com/jacobtomlinson/dask-databricks/blob/a64698074bcbe4117a0a16e32737b4fdeba3d491/dask_databricks/cli.py#L51

We should support configuring this so we can set it to other things like `dask cuda worker`. We may also want to be able to pass extra flags to `dask scheduler` and `dask worker` and we should expose that via the `dask databricks run` CLI.

```bash
#!/bin/bash

# Install Dask Databricks
/databricks/python/bin/pip install dask-databricks

# Start Dask cluster
dask databricks run --worker-command "dask cuda worker" --worker-args "--nthreads 10"
```

### PR DESCRIPTION
**Pull request by skirui-source**
Closes #10

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Thanks for this, excited to give it a spin.

One quick thought is what happens if the options the user wants to provide contains spaces?

```bash
$ dask databricks run --worker-args "--foo 'bar baz'"
```

The above example wouldn't split up cleanly. I wonder if we also want to add optional JSON support. So before calling `worker_args.split()` we try and call `json.loads(worker_args)`.

That way a user could specify a JSON list of arguments.

```bash
$ dask databricks run --worker-args "['--foo' 'bar baz']"
```

**Comment by skirui-source** [comment]
Tested my changes with the following script:

```
#!/bin/bash
set -e

pip install --upgrade pip dask[complete] git+https://github.com/skirui-source/dask-databricks.git@main dask-cuda==23.10.0 bokeh==3.2.2
pip install pyspark==3.5.0 numpy==1.23.5 scikit-learn==0.22.1
dask databricks run --worker-command "dask cuda worker" --worker-args "--nthreads 2"
```


Seeing this error on the Scheduler/Driver node:
```console
Running command git clone --filter=blob:none --quiet https://github.com/skirui-source/dask-databricks.git /tmp/pip-req-build-pixm6hlg
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
petastorm 0.12.1 requires pyspark>=2.1.0, which is not installed.
databricks-feature-store 0.14.1 requires pyspark<4,>=3.1.2, which is not installed.
ydata-profiling 4.2.0 requires numpy<1.24,>=1.16.0, but you have numpy 1.26.1 which is incompatible.
scipy 1.9.1 requires numpy<1.25.0,>=1.18.5, but you have numpy 1.26.1 which is incompatible.
mleap 0.20.0 requires scikit-learn<0.23.0,>=0.22.0, but you have scikit-learn 1.1.1 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.10.1 requires scikit-learn>=1.0.2, but you have scikit-learn 0.22.1 which is incompatible.
/databricks/python3/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
/databricks/python3/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
2023-11-09 07:32:18,796 - distributed.scheduler - INFO - -----------------------------------------------
2023-11-09 07:32:19,132 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
2023-11-09 07:32:19,168 - distributed.scheduler - INFO - State start
2023-11-09 07:32:19,174 - distributed.scheduler - INFO - -----------------------------------------------
2023-11-09 07:32:19,174 - distributed.scheduler - INFO -   Scheduler at:  tcp://10.59.230.165:8786
2023-11-09 07:32:19,175 - distributed.scheduler - INFO -   dashboard at:  http://10.59.230.165:8787/status
2023-11-09 07:32:19,175 - distributed.scheduler - INFO - Registering Worker plugin shuffle
2023-11-09 07:32:19,875 - distributed.comm.tcp - INFO - Connection from tcp://10.59.241.62:56834 closed before handshake completed
2023-11-09 07:32:19,877 - distributed.comm.tcp - INFO - Connection from tcp://10.59.249.7:34864 closed before handshake completed
2023-11-09 07:34:32,415 - distributed.scheduler - INFO - Receive client connection: Client-6c879bb7-7ed2-11ee-8e0b-00163e5e434a
2023-11-09 07:34:32,417 - distributed.core - INFO - Starting established connection to tcp://10.59.230.165:56762

**Comment by skirui-source** [comment]
and this error...from the dask worker:

```console
Running command git clone --filter=blob:none --quiet https://github.com/skirui-source/dask-databricks.git /tmp/pip-req-build-vvt7ougt
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
petastorm 0.12.1 requires pyspark>=2.1.0, which is not installed.
databricks-feature-store 0.14.1 requires pyspark<4,>=3.1.2, which is not installed.
ydata-profiling 4.2.0 requires numpy<1.24,>=1.16.0, but you have numpy 1.26.1 which is incompatible.
scipy 1.9.1 requires numpy<1.25.0,>=1.18.5, but you have numpy 1.26.1 which is incompatible.
mleap 0.20.0 requires scikit-learn<0.23.0,>=0.22.0, but you have scikit-learn 1.1.1 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.10.1 requires scikit-learn>=1.0.2, but you have scikit-learn 0.22.1 which is incompatible.
/databricks/python3/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
/databricks/python3/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
Usage: dask [OPTIONS] COMMAND [ARGS]...
Try 'dask -h' for help.

Error: No such command 'cuda'.

**Comment by jacobtomlinson** [comment]
I think the core of the problem is in this line

```
/databricks/python/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
```

I reproduced the error in a Databricks notebook to get the full traceback

```python
import importlib_metadata
[ep] = [ep for ep in importlib_metadata.entry_points(group="dask_cli") if ep.name == "cuda"]
ep.load()
```

```pytb
AttributeError: 'function' object has no attribute 'command'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-1479567383531443>, line 3
      1 import importlib_metadata
      2 [ep] = [ep for ep in importlib_metadata.entry_points(group="dask_cli") if ep.name == "cuda"]
----> 3 ep.load()

File /databricks/python/lib/python3.10/site-packages/importlib_metadata/__init__.py:209, in EntryPoint.load(self)
    204 """Load the entry point from its definition. If only a module
    205 is indicated by the value, return that module. Otherwise,
    206 return the named object.
    207 """
    208 match = self.pattern.match(self.value)
--> 209 module = import_module(match.group('module'))
    210 attrs = filter(None, (match.group('attr') or '').split('.'))
    211 return functools.reduce(getattr, attrs, module)

File /usr/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File /databricks/python/lib/python3.10/site-packages/dask_cuda/cli.py:61
     56 @click.group
     57 def cuda():
     58     """Subcommands to launch or query distributed workers with GPUs."""
---> 61 @cuda.command(name="worker", context_settings=dict(ignore_unknown_options=True))
     62 @scheduler
     63 @preload_argv
     64 @click.option(
     65     "--host",
     66     type=str,
     67     default=None,
     68     help="""IP address of serving host; should be visible to the scheduler and other
     69     workers. Can be a string (like ``"127.0.0.1"``) or ``None`` to fall back on the
     70     address of the interface specified by ``--interface`` or the default interface.""",
     71 )
     72 @click.option(
     73     "--nthreads",
     74     type=int,
     75     default=1,
     76     show_default=True,
     77     help="Number of threads to be used for each Dask worker process.",
     78 )
     79 @click.option(
     80     "--name",
     81     type=str,
     82     default=None,
     83     help="""A unique name for the worker. Can be a string (like ``"worker-1"``) or
     84     ``None`` for a nameless worker.""",
     85 )
     86 @click.option(
     87     "--memory-limit",
     88     default="auto",
     89     show_default=True,
     90     help="""Size of the host LRU cache, which is used to determine when the worker
     91     starts spilling to disk (not available if JIT-Unspill is enabled). Can be an
     92     integer (bytes), float (fraction of total system memory), string (like ``"5GB"``
     93     or ``"5000M"``), or ``"auto"``, 0, or ``None`` for no memory management.""",
     94 )
     95 @click.option(
     96     "--device-memory-limit",
     97     default="0.8",
     98     show_default=True,
     99     help="""Size of the CUDA device LRU cache, which is used to determine when the
    100     worker starts spilling to host memory. Can be an integer (bytes), float (fraction of
    101     total device memory), string (like ``"5GB"`` or ``"5000M"``), or ``"auto"`` or 0 to
    102     disable spilling to host (i.e. allow full device memory usage).""",
    103 )
    104 @click.option(
    105     "--rmm-pool-size",
    106     default=None,
    107     help="""RMM pool size to initialize each worker with. Can be an integer (bytes),
    108     float (fraction of total device memory), string (like ``"5GB"`` or ``"5000M"``), or
    109     ``None`` to disable RMM pools.
    110 
    111     .. note::
    112         This size is a per-worker configuration, and not cluster-wide.""",
    113 )
    114 @click.option(
    115     "--rmm-maximum-pool-size",
    116     default=None,
    117     help="""When ``--rmm-pool-size`` is specified, this argument indicates the maximum
    118     pool size.  Can be an integer (bytes), float (fraction of total device memory),
    119     string (like ``"5GB"`` or ``"5000M"``) or ``None``. By default, the total available
    120     memory on the GPU is used. ``rmm_pool_size`` must be specified to use RMM pool and
    121     to set the maximum pool size.
    122 
    123     .. note::
    124         This size is a per-worker configuration, and not cluster-wide.""",
    125 )
    126 @click.option(
    127     "--rmm-managed-memory/--no-rmm-managed-memory",
    128     default=False,
    129     show_default=True,
    130     help="""Initialize each worker with RMM and set it to use managed memory. If
    131     disabled, RMM may still be used by specifying ``--rmm-pool-size``.
    132 
    133     .. warning::
    134         Managed memory is currently incompatible with NVLink. Trying to enable both will
    135         result in failure.""",
    136 )
    137 @click.option(
    138     "--rmm-async/--no-rmm-async",
    139     default=False,
    140     show_default=True,
    141     help="""Initialize each worker with RMM and set it to use RMM's asynchronous
    142     allocator. See ``rmm.mr.CudaAsyncMemoryResource`` for more info.
    143 
    144     .. warning::
    145         The asynchronous allocator requires CUDA Toolkit 11.2 or newer. It is also
    146         incompatible with RMM pools and managed memory, trying to enable both will
    147         result in failure.""",
    148 )
    149 @click.option(
    150     "--rmm-release-threshold",
    151     default=None,
    152     help="""When ``rmm.async`` is ``True`` and the pool size grows beyond this value, unused
    153     memory held by the pool will be released at the next synchronization point. Can be
    154     an integer (bytes), float (fraction of total device memory), string (like ``"5GB"``
    155     or ``"5000M"``) or ``None``. By default, this feature is disabled.
    156 
    157     .. note::
    158         This size is a per-worker configuration, and not cluster-wide.""",
    159 )
    160 @click.option(
    161     "--rmm-log-directory",
    162     default=None,
    163     help="""Directory to write per-worker RMM log files to. The client and scheduler are
    164     not logged here. Can be a string (like ``"/path/to/logs/"``) or ``None`` to disable
    165     logging.
    166 
    167     .. note::
    168         Logging will only be enabled if ``--rmm-pool-size`` or ``--rmm-managed-memory``
    169         are specified.""",
    170 )
    171 @click.option(
    172     "--rmm-track-allocations/--no-rmm-track-allocations",
    173     default=False,
    174     show_default=True,
    175     help="""Track memory allocations made by RMM. If ``True``, wraps the memory
    176     resource of each worker with a ``rmm.mr.TrackingResourceAdaptor`` that
    177     allows querying the amount of memory allocated by RMM.""",
    178 )
    179 @click.option(
    180     "--pid-file",
    181     type=str,
    182     default="",
    183     help="File to write the process PID.",
    184 )
    185 @click.option(
    186     "--resources",
    187     type=str,
    188     default="",
    189     help="""Resources for task constraints like ``"GPU=2 MEM=10e9"``.""",
    190 )
    191 @click.option(
    192     "--dashboard/--no-dashboard",
    193     "dashboard",
    194     default=True,
    195     show_default=True,
    196     required=False,
    197     help="Launch the dashboard.",
    198 )
    199 @click.option(
    200     "--dashboard-address",
    201     type=str,
    202     default=":0",
    203     show_default=True,
    204     help="Relative address to serve the dashboard (if enabled).",
    205 )
    206 @click.option(
    207     "--local-directory",
    208     default=None,
    209     type=str,
    210     help="""Path on local machine to store temporary files. Can be a string (like
    211     ``"path/to/files"``) or ``None`` to fall back on the value of
    212     ``dask.temporary-directory`` in the local Dask configuration, using the current
    213     working directory if this is not set.""",
    214 )
    215 @click.option(
    216     "--shared-filesystem/--no-shared-filesystem",
    217     default=None,
    218     type=bool,
    219     help="""If `--shared-filesystem` is specified, inform JIT-Unspill that
    220     `local_directory` is a shared filesystem available for all workers, whereas
    221     `--no-shared-filesystem` informs it may not assume it's a shared filesystem.
    222     If neither is specified, JIT-Unspill will decide based on the Dask config value
    223     specified by `"jit-unspill-shared-fs"`.
    224     Notice, a shared filesystem must support the `os.link()` operation.""",
    225 )
    226 @scheduler_file
    227 @click.option(
    228     "--protocol", type=str, default=None, help="Protocol like tcp, tls, or ucx"
    229 )
    230 @click.option(
    231     "--interface",
    232     type=str,
    233     default=None,
    234     help="""External interface used to connect to the scheduler. Usually an ethernet
    235     interface is used for connection, and not an InfiniBand interface (if one is
    236     available). Can be a string (like ``"eth0"`` for NVLink or ``"ib0"`` for
    237     InfiniBand) or ``None`` to fall back on the default interface.""",
    238 )
    239 @click.option(
    240     "--preload",
    241     type=str,
    242     multiple=True,
    243     is_eager=True,
    244     help="""Module that should be loaded by each worker process like ``"foo.bar"`` or
    245     ``"/path/to/foo.py"``.""",
    246 )
    247 @click.option(
    248     "--death-timeout",
    249     type=str,
    250     default=None,
    251     help="Seconds to wait for a scheduler before closing",
    252 )
    253 @click.option(
    254     "--dashboard-prefix",
    255     type=str,
    256     default=None,
    257     help="""Prefix for the dashboard. Can be a string (like ...) or ``None`` for no
    258     prefix.""",
    259 )
    260 @tls_ca_file
    261 @tls_cert
    262 @tls_key
    263 @click.option(
    264     "--enable-tcp-over-ucx/--disable-tcp-over-ucx",
    265     default=None,
    266     show_default=True,
    267     help="""Set environment variables to enable TCP over UCX, even if InfiniBand and
    268     NVLink are not supported or disabled.""",
    269 )
    270 @click.option(
    271     "--enable-infiniband/--disable-infiniband",
    272     default=None,
    273     show_default=True,
    274     help="""Set environment variables to enable UCX over InfiniBand, implies
    275     ``--enable-tcp-over-ucx`` when enabled.""",
    276 )
    277 @click.option(
    278     "--enable-nvlink/--disable-nvlink",
    279     default=None,
    280     show_default=True,
    281     help="""Set environment variables to enable UCX over NVLink, implies
    282     ``--enable-tcp-over-ucx`` when enabled.""",
    283 )
    284 @click.option(
    285     "--enable-rdmacm/--disable-rdmacm",
    286     default=None,
    287     show_default=True,
    288     help="""Set environment variables to enable UCX RDMA connection manager support,
    289     requires ``--enable-infiniband``.""",
    290 )
    291 @click.option(
    292     "--enable-jit-unspill/--disable-jit-unspill",
    293     default=None,
    294     help="""Enable just-in-time unspilling. Can be a boolean or ``None`` to fall back on
    295     the value of ``dask.jit-unspill`` in the local Dask configuration, disabling
    296     unspilling if this is not set.
    297 
    298     .. note::
    299         This is experimental and doesn't support memory spilling to disk. See
    300         ``proxy_object.ProxyObject`` and ``proxify_host_file.ProxifyHostFile`` for more
    301         info.""",
    302 )
    303 @click.option(
    304     "--worker-class",
    305     default=None,
    306     help="""Use a different class than Distributed's default (``distributed.Worker``)
    307     to spawn ``distributed.Nanny``.""",
    308 )
    309 @click.option(
    310     "--pre-import",
    311     default=None,
    312     help="""Pre-import libraries as a Worker plugin to prevent long import times
    313     bleeding through later Dask operations. Should be a list of comma-separated names,
    314     such as "cudf,rmm".""",
    315 )
    316 @click.option(
    317     "--multiprocessing-method",
    318     default="spawn",
    319     type=click.Choice(["spawn", "fork", "forkserver"]),
    320     help="""Method used to start new processes with multiprocessing""",
    321 )
    322 def worker(
    323     scheduler,
    324     host,
    325     nthreads,
    326     name,
    327     memory_limit,
    328     device_memory_limit,
    329     rmm_pool_size,
    330     rmm_maximum_pool_size,
    331     rmm_managed_memory,
    332     rmm_async,
    333     rmm_release_threshold,
    334     rmm_log_directory,
    335     rmm_track_allocations,
    336     pid_file,
    337     resources,
    338     dashboard,
    339     dashboard_address,
    340     local_directory,
    341     shared_filesystem,
    342     scheduler_file,
    343     interface,
    344     preload,
    345     dashboard_prefix,
    346     tls_ca_file,
    347     tls_cert,
    348     tls_key,
    349     enable_tcp_over_ucx,
    350     enable_infiniband,
    351     enable_nvlink,
    352     enable_rdmacm,
    353     enable_jit_unspill,
    354     worker_class,
    355     pre_import,
    356     multiprocessing_method,
    357     **kwargs,
    358 ):
    359     """Launch a distributed worker with GPUs attached to an existing scheduler.
    360 
    361     A scheduler can be specified either through a URI passed through the ``SCHEDULER``
   (...)
    366     for info.
    367     """
    368     if multiprocessing_method == "forkserver":

AttributeError: 'function' object has no attribute 'command'
```

**Comment by jacobtomlinson** [comment]
Looks like Databricks gives us `click==8.0.4` which causes this bug. It's fixed in `>=8.1` so I've bumped the minimum version here and also made PRs upstream to do the same.

**Comment by jacobtomlinson** [comment]
Ok I got things working!

I pushed a couple of extra commits to this PR:

- Bump the minimum version of `click` to `>=8.1`
- Use `{sys.executable} -m` when calling commands because we can't always assume `dask` is on the path.

I used `g4dn.xlarge` instances for the driver and workers with proton disabled and the custom container image `databricksruntime/gpu-tensorflow:cuda11.8`.

Then I used this init script

```bash
#!/bin/bash
set -e

# Install git just so that we can install dask-databricks from source
# as it's not included in databricksruntime/gpu-tensorflow:cuda11.8.
# We can remove then when installing dask-databricks from PyPI.
apt-get update && apt-get install git -y

/databricks/python/bin/pip install --upgrade pip dask[complete] git+https://github.com/skirui-source/dask-databricks.git@main dask-cuda==23.10.0 bokeh==3.2.2
/databricks/python/bin/python -m dask databricks run --worker-command "dask cuda worker" --worker-args "--nthreads 2"
```


Screenshot 2023-11-09 at 14 20 12

**Comment by jacobtomlinson** [comment]
I cleaned things up a little further including adding a `--cuda` flag for convenience.

```bash
dask databricks run --cuda
# is equivalent to
dask databricks run --worker-command "dask cuda worker"
```

I also noticed that not pinning `dask-cuda` occasionally results in getting a super old version of `dask-cuda` (`0.18.0`).

So things work nicely now with this init script.

```bash
#!/bin/bash
set -e

# The Databricks Python directory isn't on the path in 
# databricksruntime/gpu-tensorflow:cuda11.8 for some reason
export PATH="/databricks/python/bin:$PATH"

# Install git just so that we can install dask-databricks from source
# as it's not included in databricksruntime/gpu-tensorflow:cuda11.8.
# We can remove this when installing dask-databricks from PyPI.
apt-get update && apt-get install git -y

# Install RAPIDS (cudf & dask-cudf) and dask-databricks
/databricks/python/bin/pip install --extra-index-url=https://pypi.nvidia.com \
      bokeh==3.2.2 \
      cudf-cu11 \
      dask[complete] \
      dask-cudf-cu11 \
      dask-cuda==23.10.0 \
      git+https://github.com/skirui-source/dask-databricks.git@main 

# Start the Dask cluster with CUDA workers
dask databricks run --cuda
```

**Pull request merged**
